# Generated by Django 5.0.6 on 2024-12-18 17:30

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "product_id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="รหัสสินค้า"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="ชื่อสินค้า")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="รายละเอียดสินค้า"),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="ราคาสินค้า"
                    ),
                ),
                ("quantity", models.PositiveIntegerField(verbose_name="จำนวนในสต็อก")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="วันที่เพิ่มสินค้า"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="วันที่แก้ไขล่าสุด"
                    ),
                ),
            ],
        ),
    ]
